apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-mysql
  namespace: default
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_DATABASE
          value: petclinic
        - name: MYSQL_ROOT_PASSWORD
          value: petclinic
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: sql-dir
          mountPath: /var/lib/mysql
      volumes:
      - name: sql-dir
        persistentVolumeClaim:
          claimName: petclinic-mysql-pvc
